### ISSUE TITLE
Прикрутить модульность

### ISSUE THREAD

**Issue by nibezo** [uni-jacob/jacob#62]
Добавить возможность писать кастомные модули с привязкой к уч. заведению.
- Универ (доброволец от универа) пишет модуль для подключения к ЛК, даёт доступ к данным об оценках, расписании, задолженностях и пр.

1. Проблема в доверии со стороны n-го ВУЗа
2. Проблема в сложности (не каждый ВУЗ согласится **сам** писать API)
3. Проблема в безопасности даже в том случае, если будет дан доступ и API со стороны (к вопросу о доверии)

Вариант решения с доверием: 
Найти небольшой ВУЗ. Технический. Из провинции. Зарегать себя юридически (либо попросить ВлГУ дать бумажку о том, что к тебе с их стороны есть доверие). И наработать таким образом доверие на провинциальном ВУЗе. 

Вариант 2-й: 
Отдаться ВлГУ и работать от их имени. Так доверие будет уже больше И уже можно найти через деканов/преподов их знакомых в других ВУЗах. 

Вариант 2.1-й: 
Сделать для ВлГУ в сотрудничестве с ИВЦ -> доверие.

**Comment by dadyarri** [comment]
ЦЕЛИ:
- [ ] Поговорить с Кокориным и обсудить варианты подключения к АПИ:
    - Генерировать одноразовый токен по несекурным данным (например номер зачётки или снилс)
    - Хранить логин/пароль в БД на стороне ВлГУ и получать их по необходимости

**Comment by dadyarri** [comment]
**ФИЧИ:**
- Автоматическое определение наличия плагинов для вуза и добавление их в главное меню

**Comment by dadyarri** [comment]
Cнова был у Кокорина. Предложил ему варианты авторизации. Он закидал меня законами, мол, это всё не безопасно (и я с ним согласен, т. к. передача персональных данных с их серверов на сервера моего хостинг-провайдера, затем на сервера ВК - потенциально это огромная утечка).

Насчёт расписания проблем нет, он даст все XML-ки, там ведь нет ничего секурного

**TODO** Написать ему на почту, напомнить про все варианты, он пообещал подумать чем может посодействовать.

Вообще, адекватный мужик, я согласен с его позицией касательно безопасности, в теории вся эта тема с модульностью - это большая дыра

**Comment by dadyarri** [comment]
Насчёт расписания проблем нет, он даст все XML-ки, там ведь нет ничего секурного

**Comment by nibezo** [comment]
@dadyarri Расписание даст просто в виде XML? А не доступ к базе данных расписания?
