### ISSUE TITLE
Добавить связку с Google Drive'ом группы

### ISSUE THREAD

**Issue by nibezo** [uni-jacob/jacob#68]
Предполагается, что у группы будет свой Drive и там будут лежать с разделом по семестрам и предметам файлы для учебы - литература, презентации и т.д. 

Когда какой-либо документ заливается в чат ВК группы, бот скачивает его на Drive. Как вариант в отдельную папку Inbox, откуда файлы вручную староста или другой студент могут перенести в нужно директорию формата семестр/предмет, либо бот сам понимает, в какую папку кидать по хэштегу в сообщении с документом. 

Также, как вариант, можно прямо в боте обратиться к папкам на клауде. 
Пример: 
![image](https://user-images.githubusercontent.com/52705623/110479442-70571f00-80f6-11eb-931f-be5ecdc63fbf.png)

**Comment by dadyarri** [comment]
Идея интересная, но **проблема** в хранении токенов авторизации. Будь всего одна группа, не вопрос, но когда их может быть сколько угодно... Короче, та же, ситуация, что и с влгушным лк

**Comment by nibezo** [comment]
А если как плагин? Где достаточно свой токен скинуть, для своего (для Drive группы) клауда. Можно даже автоматически там структуру папок создавать. 

Отличие от ситуации влгу' лк в том, что тут Google не против передачи токена в бота.

**Comment by dadyarri** [comment]
Дело не столько в против/не против, сколько в безопасности, это действительно хреновая практика.
Вот смотри - допустим кто-то взломает мою бд, он моментально получит доступ сразу ко всем read-write токенам
