### ISSUE TITLE
Проблема с переключением состояний при отмене призыва

### ISSUE THREAD

**Issue by MataxeP** [uni-jacob/jacob#75]
![image](https://user-images.githubusercontent.com/50626467/111795841-9e97e400-88d8-11eb-850b-42929e5fc59d.png)

**Comment by dadyarri** [comment]
Не, с этим-то порядок. Тут косяк в переключении состояний

**Comment by dadyarri** [comment]
Да, после отмены не сбрасывается стейт до `main`. Как итог - отправка любого мессаджа после отмены призыва приводит к возврату в Призыв
